Implemented MyLinkedList which implementing MyLinkedListInterface. Im…
mate-academy/jv-linked-list pull request #1086
Opened 2023-07-12 16:28 UTC by OlegStashkiv

…plemented all the required methods.

2023-07-13 09:06 UTC, holsoni requested changes
Excellent job! Sending you one advice

2023-07-13 09:06 UTC, holsoni commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        }
You already have method to check index, for it to work correctly you can add if clause:
```suggestion
        if (index != size) {
            checkIndex(index);
        }
```

2023-07-13 09:35 UTC, holsoni approved these changes

2023-07-14 12:48 UTC, Vasul-Pankiv requested changes
Please pay more attention to naming!

2023-07-14 12:48 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        }
Your solution is good, but this one is better for readability
```suggestion
           for (Node<T> x = head; x != null; x = x.next) {
                if (x.item == object || (object !=null && object.equals(x.item))) {
                    unlink(x);
                    return true;
                }
            }
```

2023-07-14 12:48 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private static class Node<T> {
make it non static and move to the end of file

2023-07-14 12:48 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/MyLinkedList.java
>      public boolean remove(T object) {
bad naming object and x rename it everywhere

2023-07-14 12:48 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private void linkFirst(T t) {
same with naming

2023-07-14 12:52 UTC, Vasul-Pankiv requested changes

2023-07-14 12:52 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        if (index < (size >> 1)) {
This better for readability
```suggestion
        if (index < (size / 2)) {
```

2023-07-14 12:52 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/MyLinkedList.java
> +
empty line

2023-07-14 12:52 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/MyLinkedList.java
> +
empty line

2023-07-14 12:52 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private Node<T> getNode(int index) {
```suggestion
    private Node<T> getNodeByIndex(int index) {
```

2023-07-17 14:05 UTC, Vasul-Pankiv approved these changes

2023-07-17 14:05 UTC, Vasul-Pankiv commented on src/main/java/core/basesyntax/MyLinkedList.java
>      public boolean remove(T object) {
Object is also not so good name. It has to be more infomative like nodeToremove

2026-05-21 08:03 UTC, closed without merging