jv-linked-list HW solution
mate-academy/jv-linked-list pull request #1189
Opened 2023-09-19 08:10 UTC by luk14n

2023-09-19 11:24 UTC, Rommelua requested changes

2023-09-19 11:24 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    static class Node<T> {
private
Private methods and classes should be after public ones in your class.

2023-09-19 11:24 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private void checkIndex(int index) {
Private methods and classes should be after public ones in your class.

2023-09-19 11:24 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            throw new IndexOutOfBoundsException("Wrong index");
msg should be more informative

2023-09-19 11:24 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        return getNode(index).value;
This is code repeating. You always check the index before getting node by index. What you should do is move the check logic INSIDE the get method.

2023-09-20 08:22 UTC, luk14n commented
can you pls also check my older HW from OOP?
 [https://github.com/mate-academy/jv-oop-advanced/pull/1251](url)
 Thanks beforehand

2023-09-20 08:23 UTC, luk14n commented
can you pls also check my older HW from OOP?
[https://github.com/mate-academy/jv-oop-advanced/pull/1251](url)
Thanks beforehand

2023-09-20 10:37 UTC, Rommelua requested changes

2023-09-20 10:37 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    static class Node<T> {
not fixed

2023-09-20 10:37 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            Node<T> currentNode = getNode(index);
![image](https://github.com/mate-academy/jv-linked-list/assets/20326858/6237c7c5-5dc2-4f0d-b967-337cfebe8b5d)

2023-09-20 10:37 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        return getNode(index).value;
![image](https://github.com/mate-academy/jv-linked-list/assets/20326858/9ad10f61-90a0-4ba5-8ba2-ce0bde21503a)

2023-09-20 10:37 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        Node<T> node = getNode(index);
![image](https://github.com/mate-academy/jv-linked-list/assets/20326858/3816a779-8413-4de5-9955-618b803446ee)

2023-09-20 10:37 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        Node<T> current = getNode(index);
![image](https://github.com/mate-academy/jv-linked-list/assets/20326858/fa85c81b-3d22-4e3a-bf87-b76482f0c033)

2023-09-20 10:37 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private Node<T> getNode(int index) {
call checkIndex here

2023-09-20 14:03 UTC, Rommelua approved these changes

2023-09-20 14:25 UTC, closed without merging