Java linked list task solution
mate-academy/jv-linked-list pull request #1191
Opened 2023-09-23 19:36 UTC by mkazarian-1

2023-09-24 09:25 UTC, sokimaaa requested changes

2023-09-24 09:25 UTC, sokimaaa commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        }
Don’t iterate your nodes from the head to tail or vice versa.

see common mistakes https://mate-academy.github.io/jv-program-common-mistakes/java-core/collections/linked-list.html

2023-09-24 09:25 UTC, sokimaaa commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    }
Private methods and classes should be after public ones in your class

see common mistakes https://mate-academy.github.io/jv-program-common-mistakes/java-core/collections/linked-list.html

2023-09-24 09:25 UTC, sokimaaa commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        }
with current implementation `remove(T object)` you iterates over list twice.
First, when you get the index.
Second, in the method `remove(int index)`, when you get the node. 

you can simplify it by adding `unlink(Node<T> node)` method.

Create a separate method`unlink(Node node)`.

See common mistakes https://mate-academy.github.io/jv-program-common-mistakes/java-core/collections/linked-list.html

2023-09-26 09:59 UTC, Rommelua approved these changes

2023-09-26 09:59 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    }
```suggestion
```

2023-09-26 09:59 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        public Node(T value, Node<T> next, Node<T> prev) {
```suggestion
        public Node(Node<T> prev, T value, Node<T> next) {
```

2023-09-26 09:59 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private void unLinked(Node<T> node) {
```suggestion
    private void unlink(Node<T> node) {
```

2024-03-16 09:48 UTC, closed without merging