added methods
mate-academy/jv-linked-list pull request #1313
Opened 2024-01-23 14:16 UTC by LizaBalshv

2024-01-23 19:32 UTC, okuzan requested changes
Make sure to read common mistakes [checklist](https://github.com/mate-academy/jv-linked-list/blob/master/checklist.md) attached to the task description before creating a PR 🙏

2024-01-23 19:32 UTC, okuzan commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    static class Node<T> {
private
better put it at the end of the file

2024-01-23 19:32 UTC, okuzan commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        Objects.checkIndex(index, size + 1);
![image](https://github.com/mate-academy/jv-linked-list/assets/49767049/1e6b5eb6-586a-4bfe-adff-eabca7b114c4)

2024-01-23 19:32 UTC, okuzan commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            add(list.get(i));
you can use for-each here

2024-01-23 19:32 UTC, okuzan commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        return removedValue;
create unlink method for `remove`s

2024-01-24 19:36 UTC, olekskov approved these changes

2024-08-15 10:50 UTC, closed without merging