release MyLinkedList
mate-academy/jv-linked-list pull request #1314
Opened 2024-01-24 11:04 UTC by u3IOm4uk

2024-01-24 19:35 UTC, olekskov requested changes

2024-01-24 19:35 UTC, olekskov commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        return current;
Please recheck checklist
https://github.com/mate-academy/jv-linked-list/blob/master/checklist.md#dont-iterate-your-nodes-from-the-head-to-the-tail-or-vice-versa

2024-01-24 19:35 UTC, olekskov commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        return removeValue;
I cannot see any actions done if current size is 1 and passed index is 0, which is valid case

2024-01-25 12:59 UTC, kozhukhovsky requested changes

2024-01-25 12:59 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/MyLinkedList.java
> +
```suggestion
```

2024-01-25 12:59 UTC, kozhukhovsky commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private static class Node<T> {
move inner class to the bottom

2024-05-09 16:07 UTC, closed without merging