Task solved according to checklist.
mate-academy/jv-linked-list pull request #1357
Opened 2024-02-27 20:52 UTC by fedaktaras

- tried to move if/else logic away or use ternary but not too much, just to keep it readable.

2024-02-28 11:10 UTC, TonyH277 requested changes
Really good job, request changes so you could edit some mistakes -> get aproved faster🥇

2024-02-28 11:10 UTC, TonyH277 commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private void initializeBase(Node<T> node) {
Minor. Just for clarity as you defined startNode and endNode

```suggestion
    private void initializeStartNode(Node<T> node) {
```

2024-02-28 11:10 UTC, TonyH277 commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private void initializeTale(Node<T> node) {
```suggestion
    private void initializeEndNode(Node<T> node) {
```

2024-02-28 11:10 UTC, TonyH277 commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private class Node<T> {
it can be made private static to clearly indicate its relationship with MyLinkedList

2024-02-28 14:59 UTC, andrii-hoienko requested changes
Good job, but some improvements required

2024-02-28 14:59 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private Node<T> findNodeFromStart(int index) {
```suggestion
    private Node<T> findNodeFromHead(int index) {
```

2024-02-28 14:59 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private Node<T> startNode;
```suggestion
    private Node<T> head;
```

2024-02-28 14:59 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private Node<T> endNode;
```suggestion
    private Node<T> tail;
```

2024-02-28 14:59 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        Node<T> x = startNode;
```suggestion
        Node<T> currentNode = startNode;
```

2024-02-28 14:59 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        Node<T> x = endNode;
```suggestion
        Node<T> currentNode = endNode;
```

2024-02-28 14:59 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        throw new IndexOutOfBoundsException("Index " + index + " out of bounds.");
```suggestion
        if (index > size && index <= 0) {
            throw new IndexOutOfBoundsException("Index " + index + " out of bounds.");
        }
        
```

2024-02-28 14:59 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/MyLinkedList.java
>      }
These methods used only once and significantly increase complexity, so I suggest creating methods addToHead and addToTail and use them where you need

2024-02-28 14:59 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        startNode.previous = node;
You have kind of 2 methods to set head linkFirst and initializeStart node i suggest to collaplse them (as well as linkLast and initializeEnd)

2024-02-28 14:59 UTC, andrii-hoienko commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        }
I believe here you should just call unlink

2024-02-29 10:16 UTC, karma-o requested changes

2024-02-29 10:16 UTC, karma-o commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private void indexValidation(int index) {
method names should be verbs
```suggestion
    private void validateIndex(int index) {
```

2024-02-29 10:16 UTC, karma-o commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        throw new IndexOutOfBoundsException("Index " + index + " out of bounds.");
not resolved

2024-02-29 10:16 UTC, karma-o commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        private Node(T data, Node<T> next, Node<T> previous) {
constructors should not have any logic inside them, only variable assignments or calls to other constructors

2024-02-29 15:57 UTC, yevheniisynytsia approved these changes
you didn't fix mentor's comments about naming, please consider this comments
it is important to learn how to name methods and variables

2025-05-28 09:58 UTC, closed without merging