Implemented all the required methods in the MyLinkedList class
mate-academy/jv-linked-list pull request #446
Opened 2022-01-30 12:39 UTC by dima-semeniuk

2022-01-31 10:01 UTC, yurii-tomashevskyi commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        if (index > size || index < 0) {
beter create method checkElementIndex(int index). You use this if statement - 4 times

2022-01-31 11:24 UTC, yurii-tomashevskyi approved these changes
Good job 🏆🔥

2022-02-01 11:46 UTC, AlexRozv requested changes

2022-02-01 11:46 UTC, AlexRozv commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        return removedNodeValue;
https://mate-academy.github.io/jv-program-common-mistakes/java-core/collections/linked-list.html#create-a-separate-method-unlinknode-node

let's create a separate method that will unlink our node

also, we can simplify this like this:
we can create temporary nodes node.prev and node.next, then do two checks:
if (prev == null) {...}
else {...}
if (next == null) {...}
else {...}

2022-02-01 12:55 UTC, AlexRozv approved these changes
good job 👍

2023-09-29 14:50 UTC, closed without merging