my hw jv-linked-list
mate-academy/jv-linked-list pull request #627
Opened 2022-08-10 13:48 UTC by fifahater

2022-08-10 14:12 UTC, DioStesso1 requested changes

2022-08-10 14:12 UTC, DioStesso1 commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    public class Node<T> {
Let's set the private modifier to this inner class. So that the others won't be able to get access from outside of the class.

2022-08-10 14:12 UTC, DioStesso1 commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        addLast(value);
The method is supposed to add nodes to the end anyway. You should not make 2 methods for this.

2022-08-10 14:12 UTC, DioStesso1 commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            for (Node<T> i = first; i != null; i = i.next) {
It's able to combine these 2 methods. Rewrite 2 conditions into only one.

2022-08-10 14:33 UTC, Dio-Stesso requested changes

2022-08-10 14:33 UTC, Dio-Stesso commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            } else if (object != null && object.equals(i.item)) {
Merge this condition to the first one by using logical operator || (OR). Your "if" body repeated twice.

2022-08-10 14:49 UTC, Dio-Stesso approved these changes
Passing the PR to mentors.

2022-08-11 07:45 UTC, Noct2000 requested changes

2022-08-11 14:04 UTC, Noct2000 requested changes

2022-08-11 14:04 UTC, Noct2000 commented on src/main/java/core/basesyntax/MyLinkedList.java
> +                    + index);
```suggestion
```

2022-08-11 14:04 UTC, Noct2000 commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            addBefore(value, getNodeByIndex(index));
```suggestion
            checkIndex(index);
            addBefore(value, getNodeByIndex(index));
```

2022-08-11 14:15 UTC, Noct2000 approved these changes

2024-09-17 20:25 UTC, closed without merging