done homework
mate-academy/jv-linked-list pull request #652
Opened 2022-08-11 12:10 UTC by Rossoline

2022-08-11 12:34 UTC, KosatskiyKirill commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            head = tail = newNode;
Може цю перевірку замінити на size == 0
або додати іі в окремий метод

2022-08-11 12:36 UTC, KosatskiyKirill commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            tail = newNode;
також

2022-08-11 12:53 UTC, Rossoline commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            head = tail = newNode;
Disagree with you. We get different Node back.

2022-08-11 12:53 UTC, Rossoline commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            tail = newNode;
The same.

2022-08-11 12:56 UTC, KosatskiyKirill approved these changes

2022-08-11 12:56 UTC, KosatskiyKirill commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            head = tail = newNode;
Ok, then mentor will decide

2022-08-11 14:12 UTC, Sofasmile requested changes

2022-08-11 14:12 UTC, Sofasmile commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        } else if (index == 0) {
```suggestion
         if (index == 0) {
```

2022-08-11 14:12 UTC, Sofasmile commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            if (get(i) == object || get(i) != null && get(i).equals(object)) {
we have to iterate over the nodes and search for the correct node and pass it to unlink() method
because now the complexity of this method is o(n^2)

2022-08-11 14:12 UTC, Sofasmile commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        for (int i = 0; i < index; i++) {
if the index is in the first part of list, let's start movement from the head, otherwise from the tail

2022-08-15 12:48 UTC, dSkarzh approved these changes

2022-12-06 06:30 UTC, Sofasmile approved these changes

2026-03-29 17:40 UTC, closed without merging