MyLinkedList methods implemented. Nested Class Node created
mate-academy/jv-linked-list pull request #657
Opened 2022-08-20 00:41 UTC by SpaceUrgent

2022-08-20 09:04 UTC, aaananas requested changes

2022-08-20 09:04 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        return (T) getNodeByIndex(index).value;
```suggestion
        return (T) getNodeByIndex(index).value;
```

2022-08-20 09:04 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        }
```suggestion
```
your code should work without this

2022-08-20 09:04 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        }
![image](https://user-images.githubusercontent.com/81781479/185737804-fec659d9-db6d-4f27-835c-dcb6b7f5f630.png)

move this to method unlink

2022-08-22 10:07 UTC, MaliukDaria requested changes

2022-08-22 10:07 UTC, MaliukDaria commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            throw new IndexOutOfBoundsException();
not informative exception message

2022-08-22 10:07 UTC, MaliukDaria commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        unlinkedNode.next.previous = unlinkedNode.previous;
could we simplify this?

2022-08-22 14:31 UTC, aaananas requested changes

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        Node newNode = new Node<>(value);
```suggestion
        Node<T> newNode = new Node<>(value);
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        Node currentNode = getNodeByIndex(index);
```suggestion
        Node<T> newNode = new Node(value);
        Node<T> currentNode = getNodeByIndex(index);
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        return (T) getNodeByIndex(index).value;
```suggestion
        return getNodeByIndex(index).value;
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        Node current = getNodeByIndex(index);
```suggestion
        Node<T> current = getNodeByIndex(index);
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        replacedValue = (T) current.value;
```suggestion
        replacedValue = current.value;
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        Node currentNode = head;
```suggestion
        Node<T> currentNode = head;
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +                    || currentNode.value.equals(object) && currentNode.value != null) {
```suggestion
                    || currentNode.value != null && currentNode.value.equals(object)) {
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        Node newNode = new Node(value);
```suggestion
        Node<T> newNode = new Node<>(value);
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private void insertBefore(Node currentNode, Node newNode) {
```suggestion
    private void insertBefore(Node<T> currentNode, Node<T> newNode) {
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        Node currentNode;
```suggestion
        Node<T> currentNode;
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private Node getNodeByIndex(int index) {
```suggestion
    private Node<T> getNodeByIndex(int index) {
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private T unlinkNode(int index) {
```suggestion
    private T unlinkNode(Node<T> node) {
```
try to think about how to implement this method with a node as a parameter.
If would be more efficient. When you have to unlink a node by index, you invoke the method getNodeByIndex() and pass the node in this method. Iteration over the whole list would be done just once - when looking for this node in the method getNodeByIndex()

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +                unlinkNode(i);
```suggestion
                unlinkNode(currentNode);
```
Here you are iterating over the whole list, you find the node!, then pass an index, and iterate again in the method uninkNode(). Basically doing the same thing twice

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        if (index == 0) {
```suggestion
        if (node == head) {
```
You can compare references

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        }
```suggestion
        if (node == tail) {
            return unlinkLast(tail);
        }
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        unlinkedNode.next.previous = unlinkedNode.previous;
```suggestion
        node.previous.next = node.next;
        node.next.previous = node.previous;
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        return (T) unlinkedNode.value;
```suggestion
        return unlinkedNode.value;
```

2022-08-22 14:31 UTC, aaananas commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private T unlinkFirst(Node node) {
```suggestion
    private T unlinkFirst(Node<T> node) {
```
raw usage of a parametrized class is not suggested

2022-08-22 17:42 UTC, zachar-chorny requested changes
Not all edits were made
<img width="785" alt="Screen Shot 2022-08-22 at 8 42 02 PM" src="https://user-images.githubusercontent.com/90692308/185985148-0b923ec8-1ea1-4165-94e1-3c010f8d52fc.png">

2022-08-22 18:20 UTC, zachar-chorny approved these changes

2025-03-09 18:18 UTC, closed without merging