Linked list methods implementation
mate-academy/jv-linked-list pull request #855
Opened 2023-01-19 17:11 UTC by Dmytro-Byrka

2023-01-19 18:52 UTC, andriy-shulepa requested changes

2023-01-19 18:52 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private static class Node<T> {
Inner classes should be defined at the bottom of the file

2023-01-19 18:52 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            node.prev = tail;
you can initialize prev using constructor

2023-01-19 18:52 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        if (!isPositionIndex) {
you can get rid of the inverted check by rewriting your condition to 
if (index < 0 || index >= size)

2023-01-19 18:52 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            throw new IndexOutOfBoundsException("Passed index: " + index + " is invalid");
add size to message, please

2023-01-19 18:52 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            return;
unnecessary return statement

2023-01-19 18:52 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        checkIndex(index);
check index validation is present in getNode method

2023-01-20 16:31 UTC, Dmytro-Byrka commented
I have fixed errors

2023-01-23 19:10 UTC, aleksandr-bevza approved these changes

2025-04-11 18:38 UTC, closed without merging