implemented MyLinkedList class
mate-academy/jv-linked-list pull request #885
Opened 2023-02-17 13:47 UTC by outref

2023-02-17 14:36 UTC, Yehor-Cherkashyn requested changes

2023-02-17 14:36 UTC, Yehor-Cherkashyn commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            if (Objects.equals(node.item, item)) {
In common mistakes says: "Don't use class Objects"

2023-02-23 08:31 UTC, Yehor-Cherkashyn approved these changes

2023-02-23 08:38 UTC, nacenik approved these changes
Good job! 
Keep it up! 🔥

2025-08-25 04:06 UTC, closed without merging