Implementation of LinkedList
mate-academy/jv-linked-list pull request #957
Opened 2023-03-18 19:50 UTC by fed4ik

2023-03-19 10:43 UTC, andriy-shulepa requested changes

2023-03-19 10:43 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        if ((index >= 0) && (index == size)) {
```suggestion
        if (index == size) {
```
index >= 0 is already validated in checkIndexForAdd method

2023-03-19 10:43 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        }
is this code reachable? last node will be removed previously as regular node

2023-03-19 10:43 UTC, andriy-shulepa commented on src/main/java/core/basesyntax/MyLinkedList.java
> +            for (Node<T> node = firstNode; node != null; node = node.next) {
```suggestion
            for (Node<T> node = firstNode; node.next != null; node = node.next) {
```

2023-03-20 12:38 UTC, Rommelua requested changes

2023-03-20 12:38 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        }
```suggestion
        if (object == null) {
            for (Node<T> node = firstNode; node.next != null; node = node.next) {
                if (node.item == null) {
                    unlink(node);
                    return true;
                }
            }
        } else {
            for (Node<T> node = firstNode; node.next != null; node = node.next) {
                if (object.equals(node.item)) {
                    unlink(node);
                    return true;
                }
            }
        }
```

2023-03-20 12:38 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +    private void checkIndexForAdd(int index) {
this method can be deleted

2023-03-20 12:38 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        public T getItem() {
delete get/set in this class

2023-03-21 10:25 UTC, Rommelua approved these changes

2023-03-21 10:25 UTC, Rommelua commented on src/main/java/core/basesyntax/MyLinkedList.java
> +        size++;
![image](https://user-images.githubusercontent.com/20326858/226578754-2b420a0d-c69b-47e1-ac39-73986e975e42.png)

2026-05-14 09:37 UTC, closed without merging